{{- if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-ci
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    # kubernetes.io/ingress.class: nginx
    #acme.cert-manager.io/http01-edit-in-place: "true"
  name: {{ include "hive.fullname" $ }}{{"-nginx-ingress"}}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ include "hive.fullname" . }}
            port:
              number: {{ .Values.ingress.port | int }}
  tls:
  - hosts:
      - {{ .Values.ingress.host}}
    secretName: {{ include "hive.fullname" $ }}{{"-nginx-ingress-secret"}}
  {{- end }}