{{- if .Values.serviceEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}
  labels:
  {{- include "hive.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type}}
  ports:
    {{- range .Values.service.ports}}
    - port: {{.port}}
      targetPort: {{.targetPort}}
      nodePort: {{.nodePort}}
      name: {{.name}}
      protocol: TCP
  {{- end}}

  selector:
  {{- include "hive.selectorLabels" . | nindent 4 }}
  {{- end}}